services:
    iginx: 
        container_name :
            "${PROJECT_NAME}_nginx"

        build: 
            context:
                ./docker/nginx
            dockerfile: Dockerfile
            
        depends_on:
            - app
            - mariadb
        volumes:
            - ./:/var/www/baseProject/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/nginx.d:/etc/nginx/conf.d
            
        working_dir: /var/www
        
        ports:
            - 80:80
        networks:
            - baseProject

    app: 
        container_name: "${PROJECT_NAME}_php"
        build: 
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                PROJECT_NAME: "${PROJECT_NAME}"
                user: musta
                uid: 1000

        depends_on:
            - mariadb

        working_dir: /var/www/${PROJECT_NAME}/

        volumes:
            - ./:/var/www/${PROJECT_NAME}/

        networks:
            - ${PROJECT_NAME}


    mariadb:
        image: mariadb:latest
        container_name: "${PROJECT_NAME}_mysql"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '${DB_HOST}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'YES'
            command: mysql --character-set-server=utf8mb4 --collaction-server
        volumes:
            - 'baseProject_mysql:/data'
            
        ports:
            - 3306:3306
        networks:
            - baseProject

    selenium:
        image: 'selenium/standalone-chrome'
        extra_hosts:
        - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - baseProject

networks:
        baseProject:
            driver: bridge

volumes:
    baseProject_mysql:
        driver: local

  