version: "3.7"
services:
    iginx: 
        container_name :
            "${PROJECT_NAME}_nginx"

        build: 
            context:
                ./docker/nginx
            dockerfile: Dockerfile
            
        depends_on:
            - app
        volumes:
            - ./:/var/www/vhost/baseProject/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/nginx.d:/etc/nginx/conf.d
            # - ./docker/nginx/ssl:/etc/nginx/ssl
            
        working_dir: /var/www/vhost
        
        ports:
            - '80:80'
            # - '9008:9008'
        networks:
            - baseProject
        # labels:
        #     - 'traefik.http.routers.${PROJECT_NAME}_nginx.rule=HostRegexp(`${APP_DOMAIN}`,`{subdomain:[a-z]+.${APP_DOMAIN}}`)'
        #     - 'traefik.http.routers.${PROJECT_NAME}_nginx.priority=1'
        #     - 'traefik.docker.network=proxy'

    app: 
        container_name: "${PROJECT_NAME}_php"
        build: 
            context: ./docker/php
            dockerfile: Dockerfile

            args:
                user: 'musta'
                uid: 1000
        
        environment:
                PHP_MEMORY_LIMIT: '512M'
                COMPOSER_MEMORY_LIMIT: '-1'

        working_dir: /var/www/vhost/${PROJECT_NAME}/

        volumes:
            - ./:/var/www/vhost/${PROJECT_NAME}/

        ports:
            - '9003:9003'


        networks:
            - ${PROJECT_NAME}

    mysql:
        image: mariadb:10
        container_name: "${PROJECT_NAME}_mysql"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '${DB_HOST}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'YES'
            command: mysql --character-set-server=utf8mb4 --collaction-server
        volumes:
            - 'baseProject_mysql:/data'
            
        ports:
            - 3306:3306
        networks:
            - baseProject


networks:
        baseProject:
            driver: bridge

volumes:
    baseProject_mysql:
        driver: local

  